### ISSUE TITLE
screenshot demonstrating it in action?

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/JqueryChosen#11]
If this is not already part of mantis 2.x then I'd love to see a screenshot of it in action. Thanks in advance!

**Comment by kivervinicius** [comment]
THIS IS THE SAME https://harvesthq.github.io/chosen/

**Comment by luzpaz** [comment]
if we decide to use this plugin then I'll try to remember to submit some screenshots so people can see how it looks like implemented in mantisbt. thanks
