### ISSUE TITLE
Getting security error in Chrome 56.0.2924.87

### ISSUE THREAD

**Issue by mludlum** [mantisbt-plugins/JqueryChosen#12]
I have Mantis 2.1 and installed the jqueryChosen plugin.   The injected javascript is rejected by Chrome with this error:

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-diiMkycBpF9oEr821YkulW2qL+FjsI6pCAHuqKiElb0='), or a nonce ('nonce-...') is required to enable inline execution.

On this line  

<link rel="stylesheet" type="text/css" href="/track/plugin_file.php?file=JqueryChosen/chosen.css" /><script type="text/javascript" src="/track/plugin_file.php?file=JqueryChosen/chosenmin.js"></script><script type="text/javascript" src="/track/plugin_file.php?file=JqueryChosen/chosen.js"></script><script> var SELECTION_ONE_OPTION = "Selection one Option.";var NO_RESULTS = "No results here!";</script><link rel="stylesheet" type="text/css" href="/track/plugin_file.php?file=BBCodePlus/bbcodeplus.css" /><script type="text/javascript" src="/track/plugin_file.php?file=BBCodePlus/bbcodeplus-init.js"></script><link rel="stylesheet" type="text/css" href="/track/plugin_file.php?file=BBCodePlus/prism/styles/default.css" /><script type="text/javascript" src="/track/plugin_file.php?file=BBCodePlus/prism/prism.js"></script></head>

**Comment by mludlum** [comment]
I put this hack in JqueryChosen.php to get around the issue because I could not figure out how to source a php file located in a plugin folder in a script tag.  Easy to do in Wordpress.   The hack writes a file for every page hit which is obviously not good.  Had to chmod the plugin and files folder to give apache write permissions.

    function resources($p_event)
    {
        $t_file_path = config_get( 'plugin_path' ).'JqueryChosen'.DIRECTORY_SEPARATOR.'files'.DIRECTORY_SEPARATOR.'jsconfig.js';
        $script = 'var SELECTION_ONE_OPTION = "' . plugin_lang_get("selectionOneOption") . '";' .
            'var NO_RESULTS = "' . plugin_lang_get("noResults") . '";' ;
        file_put_contents($t_file_path, $script);


        $resources .= '<link rel="stylesheet" type="text/css" href="' . plugin_file('chosen.css') . '" />' .
            '<script type="text/javascript" src="' . plugin_file('chosenmin.js') . '"></script>' .
            '<script type="text/javascript" src="' . plugin_file('chosen.js') . '"></script>' .
            '<script type="text/javascript" src="' . plugin_file('jsconfig.js') . '"></script>' ;

        return $resources;
    }
`

**Comment by luzpaz** [comment]
@kivervinicius can you weigh in on this ?

**Comment by kivervinicius** [comment]
Hi, I am currently without the current version of the mantis, would have any url for testing?

**Comment by mludlum** [comment]
Sorry, I don't because I have my patch installed in my installation.  I'm surprised this doesn't occur on older installations.  It's an issue that occurs on newer versions of browsers with stricter security.

**Comment by kivervinicius** [comment]
solved in last version.
