### ISSUE TITLE
Mantis loads wrong MIMEtype of .png from Plugin "Jquery Chosen 0.2"

### ISSUE THREAD

**Issue by NeumannPSG** [mantisbt-plugins/JqueryChosen#8]
We installed the Plugin Jquery Chosen 0.2 on our MantisBT 1.2.20 System.
It is working like expected. The only problem is that Chrome (Version
53.0.2785.143 m) and IE (Version 11.589.10586.0) aren't loading the chosen-sprite.png from the plugin. Firefox (49.0.1) is fine. Because of the missing sprite the small X isn't shown.
Without that it is impossible to deselect on Single Selects.
By debugging this problem we find out that the Browsers get the wrong MIMEtype from the .png. They interpret it as a plain Type.

Any Ideas to find a Solution would be nice.

**Comment by kivervinicius** [comment]
What is the application server that is being used, your server is not accepting the correct mimeType.

**Comment by NeumannPSG** [comment]
Mantis is running on Windows Server 2012 R2 with an Apache2. In the mime.types configfile from Apache is .png enabled (image/png	png).

**Comment by kivervinicius** [comment]
Sorry but i don't know what is this, verify on your server configuration, because the problem don't related with this plugin.
